version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database
      MYSQL_USER: iissi_user
      MYSQL_PASSWORD: iissi_password
    ports:
        - 3306:3306
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
  
  silence:
    build: .
    depends_on:
      - db
    environment:
      - "GIT_USER=${GIT_USER}"
      - "GIT_PASS=${GIT_PASS}"      
      - "GIT_REPO=${GIT_REPO}"
    ports:
      - 8080:8080
    